# Generated by Django 3.2.5 on 2021-12-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('className', models.CharField(max_length=100)),
                ('courseID', models.CharField(max_length=50)),
                ('teacher', models.EmailField(max_length=100)),
                ('classTeacherMail', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('classCode', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
