# Generated by Django 3.2.5 on 2021-12-14 10:55

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0002_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='video',
            field=embed_video.fields.EmbedVideoField(default='hello'),
            preserve_default=False,
        ),
    ]
